### ISSUE TITLE
Kicker.RunnerModel (calculator, unitconverter, services, places, desktopsessiones, PowerDevil"

### ISSUE THREAD

**Issue by migzulk28** [adhec/launchpad-plasma#1]
Kicker.RunnerModel {
        id: runnerModel
        appletInterface: plasmoid
        runners: {
            var runners = ["desktopsessions", "services", "places",
                           "PowerDevil", "calculator", "unitconverter"];

            if (plasmoid.configuration.useExtraRunners) {
                runners = runners.concat(plasmoid.configuration.runners);
            }
            return runners;
        }
        mergeResults: true
        favoritesModel: globalFavorites
    }

**Comment by adhec** [comment]
Extra runners have new interface in plasma 5.27. Thanks
